### ISSUE TITLE
System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by Androxilogin** [Entoarox/StardewMods#11]
Continually coming across this error with '-1' tiles.

   {
      "MapName": "SeedShop",
      "LayerId": "Buildings",
      "TileIndex": -1,
      "TileX": 2,
      "TileY": 5,
      "Optional": false,
	  "Conditions": "marriedAbigail"
    },

[17:12:02 ERROR SMAPI] Advanced Location Loader requested an immediate game shutdown: Unable to patch tile, a unexpected error occured: Tile(SeedShop@[2,5]:Buildings = `-1`)
System.ArgumentNullException: Value cannot be null.
Parameter name: index
   at Entoarox.Framework.Extensions.GameLocationExtensions.SetTile(GameLocation self, Int32 x, Int32 y, String layer, Int32 index, String sheet)
   at Entoarox.AdvancedLocationLoader.Processors.ApplyTile(Tile tile)
[17:12:02 TRACE Advanced Location Loader] Tile(SeedShop@[3,6]:Back = `607`) ~> true

[Spouses Move Out.txt](https://github.com/Entoarox/StardewMods/files/718140/Spouses.Move.Out.txt)

**Comment by Androxilogin** [comment]
This is actually happening once other mods are loaded alongside of others. I'm correcting one by one then adding others to edit against one at a time but keep getting this error in mods fixed previously while new mods added don't touch on these tiles so it isn't a conflict. I've tried adding the sheetid which actually worked on some occasions.
