### ISSUE TITLE
Seasonal conditions in shops are not working.

### ISSUE THREAD

**Issue by Androxilogin** [Entoarox/StardewMods#6]
Example: 

    {
      "Id": 299,
	  "conditions": "fall"
    },

This will cause the shop to display "out of stock" upon entering the menu.

// **Now testing the seasonal condition overall..**
  
  /Note in Pierre's:
  
   {
      "MapName": "SeedShop",
      "LayerId": "Front",
      "TileX": 40,
      "TileY": 7,
      "TileIndex": -1,
	  "Conditions": "summer",
      "Optional": false
    },

[12:11:56 ERROR Advanced Location Loader] Unable to load manifest, a unexpected error occured: C:\Program Files\Games\Stardew Valley\Mods\AdvancedLocationLoader\locations\CleanupCrew\manifest.json
Unable to cast object of type '<IntersectIterator>d__69`1[System.String]' to type 'System.String[]'.
   at Entoarox.Framework.Conditions.FindConflictingConditions(String conds, Char seperator, Int32 limit, Boolean strict)
   at Entoarox.AdvancedLocationLoader.Loaders.Loader1_2.Parse(String filepath, LocationConfig1_2 config)
   at Entoarox.AdvancedLocationLoader.Loaders.Loader1_2.Load(String filepath)

/Note that !summer shows no error. I haven't tested if it's working but no error is displayed in the console.

Same result with overrides.

/ Tested the married condition afterwards and it worked fine.

[SeedShop Summer Condition.txt](https://github.com/Entoarox/StardewMods/files/717340/SeedShop.Summer.Condition.txt)

**Comment by Entoarox** [comment]
For some reason the conflict resolution is not working as intended, I will disable it for now, and people will just need to manually figure out why their conditions are not working....
