### ISSUE TITLE
Testing time condition

### ISSUE THREAD

**Issue by Androxilogin** [Entoarox/StardewMods#9]
Same tile again, only with a time condition.
 
   {
      "MapName": "SeedShop",
      "LayerId": "Front",
      "TileX": 40,
      "TileY": 7,
      "TileIndex": -1,
	  "Conditions": "time=1200",
      "Optional": false
    },

[12:27:41 ERROR SMAPI] Advanced Location Loader requested an immediate game shutdown: Unable to patch tile, a unexpected error occured: Tile(SeedShop@[40,7]:Front = `-1`)
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Entoarox.AdvancedLocationLoader.AdvancedLocationLoaderMod.ConditionResolver(String condition)
   at Entoarox.Framework.Conditions.CheckCondition(String condition, Func`2 customResolver)
   at Entoarox.Framework.Conditions.CheckConditionList(String conditionlist, Func`2 customResolver, Char seperator, Int32 limit)
   at Entoarox.AdvancedLocationLoader.Processors.ApplyTile(Tile tile)
   
   
/ time> shows no error but also does not apply the condition.
/ replaced time with earthquake condition afterward with success.
/ houseLevel= also tested and working correctly.
/ farmType= tested and working correctly.

[Time Equals Condition.txt](https://github.com/Entoarox/StardewMods/files/717347/Time.Equals.Condition.txt)

**Comment by Entoarox** [comment]
There is no `time=%%` condition, as that would only be valid for 10 in-game minutes I felt it overkill to add, there is a `time>%%` condition.

Also note that the time condition is for shops and other dynamic triggers only, tiles are only guaranteed to be updated once a in-game day, as updating them more often has a large impact on the code.

**Comment by Androxilogin** [comment]
I wasn't sure how time=%% was to react. I agree, overkill extreme. Resolved by understanding, I'll update my notes.

**Comment by Entoarox** [comment]
I am closing this as incorrect information.
